# Interface to run CARP on
IF=lan

# Virtual IP shared with the other system
VIP=192.168.111.254

# Size of the network mask for the virtual IP
VMASK=24

# Real, static IP of this host
# (default is primary adress of $IF interface)
MYIP=

# Password shared with the other system
PASSWORD=password

# IP addresses to arping after taking over the shared IP,
# you should list all known systems, those not listed can
# take up to a minute to notice the change.
PINGIP=""

# Additional options
OPTIONS="--advbase=10 --advskew 128 --shutdown"
